# Generated by Django 4.2 on 2023-05-05 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='team_membership',
            new_name='team',
        ),
        migrations.AddField(
            model_name='task',
            name='viewers',
            field=models.ManyToManyField(related_name='viewed_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
