# Generated by Django 4.2 on 2023-05-03 11:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("custom_user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appuser",
            name="role",
        ),
    ]
